import {
  defaultOutput1Settings,
  defaultOutput2Settings,
} from '../context/lyricsStore/outputSlice.js';
import { defaultStageSettings } from '../context/lyricsStore/stageSlice.js';

const baseOutputSettings = { ...defaultOutput1Settings };

export const outputTemplates = [
  {
    id: 'default',
    title: 'Default',
    description: 'Reset to default application settings with standard configuration',
    getSettings: (outputKey) => {
      return outputKey === 'output2' ? { ...defaultOutput2Settings } : { ...defaultOutput1Settings };
    }
  },
  {
    id: 'transparent-lower-third',
    title: 'Transparent Lower Third',
    description: 'Clean overlay for camera feeds, OBS scenes, and existing visual backgrounds',
    settings: {
      ...baseOutputSettings,
      fontStyle: 'Inter',
      fontSize: 52,
      fontColor: '#FFFFFF',
      translationLineColor: '#FDE68A',
      dropShadowOpacity: 7,
      dropShadowOffsetY: 8,
      dropShadowBlur: 16,
      backgroundOpacity: 0,
      lyricsPosition: 'lower',
      transitionAnimation: 'fade',
      transitionSpeed: 250,
      maxLinesEnabled: true,
      maxLines: 2,
      minFontSize: 32,
      xMargin: 5.5,
      yMargin: 2.5,
    }
  },
  {
    id: 'transparent-center-focus',
    title: 'Transparent Center Focus',
    description: 'Centered transparent lyrics for simple projection over motion or still backgrounds',
    settings: {
      ...baseOutputSettings,
      fontStyle: 'Lato',
      fontSize: 58,
      fontColor: '#FFFFFF',
      translationLineColor: '#FCD34D',
      dropShadowOpacity: 8,
      dropShadowOffsetY: 9,
      dropShadowBlur: 18,
      backgroundOpacity: 0,
      lyricsPosition: 'center',
      transitionAnimation: 'fade',
      transitionSpeed: 300,
      maxLinesEnabled: true,
      maxLines: 3,
      minFontSize: 34,
      xMargin: 6,
      yMargin: 1.5,
    }
  },
  {
    id: 'transparent-lyric-video-impact',
    title: 'Transparent Lyric Video Impact',
    description: 'Bold no-band style for sing-alongs where the background should stay visible',
    settings: {
      ...baseOutputSettings,
      fontStyle: 'Bebas Neue',
      fontSize: 72,
      fontColor: '#FFE66D',
      bold: true,
      allCaps: true,
      borderColor: '#000000',
      borderSize: 2,
      dropShadowOpacity: 9,
      dropShadowOffsetY: 10,
      dropShadowBlur: 16,
      backgroundOpacity: 0,
      lyricsPosition: 'lower',
      transitionAnimation: 'slide',
      transitionSpeed: 180,
      maxLinesEnabled: true,
      maxLines: 2,
      minFontSize: 42,
      xMargin: 4,
      yMargin: 2,
    }
  },
  {
    id: 'worship-lower-band',
    title: 'Worship Lower Band',
    description: 'Readable lower-third band for church projection over cameras or ambient backgrounds',
    settings: {
      ...baseOutputSettings,
      fontStyle: 'Inter',
      fontSize: 54,
      fontColor: '#FFFFFF',
      translationLineColor: '#FDE68A',
      bold: true,
      dropShadowOpacity: 5,
      dropShadowOffsetY: 6,
      dropShadowBlur: 12,
      backgroundColor: '#07111F',
      backgroundPaint: {
        type: 'linear',
        angle: 90,
        stops: [
          { color: '#07111F', position: 0 },
          { color: '#123047', position: 100 },
        ],
      },
      backgroundOpacity: 7,
      backgroundBandHeightMode: 'custom',
      backgroundBandCustomLines: 2,
      backgroundBandVerticalPadding: 28,
      lyricsPosition: 'lower',
      transitionAnimation: 'fade',
      transitionSpeed: 250,
      maxLinesEnabled: true,
      maxLines: 2,
      minFontSize: 34,
      xMargin: 5.5,
      yMargin: 2.5,
    }
  },
  {
    id: 'livestream-subtitle-band',
    title: 'Livestream Subtitle Band',
    description: 'Compact band for mixed camera feeds where text must stay readable',
    settings: {
      ...baseOutputSettings,
      fontStyle: 'Roboto',
      fontSize: 42,
      bold: true,
      fontColor: '#FFFFFF',
      translationLineColor: '#FBBF24',
      borderSize: 0,
      dropShadowOpacity: 4,
      dropShadowOffsetY: 4,
      dropShadowBlur: 10,
      backgroundColor: '#000000',
      backgroundOpacity: 6,
      backgroundBandHeightMode: 'custom',
      backgroundBandCustomLines: 2,
      backgroundBandVerticalPadding: 18,
      lyricsPosition: 'lower',
      transitionAnimation: 'fade',
      transitionSpeed: 180,
      maxLinesEnabled: true,
      maxLines: 2,
      minFontSize: 30,
      xMargin: 8,
      yMargin: 1.25,
    }
  },
  {
    id: 'bilingual-two-line',
    title: 'Bilingual Two-Line',
    description: 'Two-line lower band tuned for lyrics with translations or response lines',
    settings: {
      ...baseOutputSettings,
      fontStyle: 'Noto Sans',
      fontSize: 46,
      translationFontSizeMode: 'custom',
      translationFontSize: 38,
      fontColor: '#FFFFFF',
      translationLineColor: '#93C5FD',
      lineSpacing: 1.06,
      dropShadowOpacity: 5,
      dropShadowOffsetY: 5,
      dropShadowBlur: 10,
      backgroundColor: '#111827',
      backgroundOpacity: 8,
      backgroundBandHeightMode: 'custom',
      backgroundBandCustomLines: 2,
      backgroundBandVerticalPadding: 26,
      lyricsPosition: 'lower',
      transitionAnimation: 'fade',
      transitionSpeed: 220,
      maxLinesEnabled: true,
      maxLines: 2,
      minFontSize: 30,
      xMargin: 7,
      yMargin: 2,
    }
  },
  {
    id: 'reading-center-band',
    title: 'Centered Lyric Band',
    description: 'Mid-screen band for longer lyric passages that benefit from extra line capacity',
    settings: {
      ...baseOutputSettings,
      fontStyle: 'Open Sans',
      fontSize: 48,
      fontColor: '#F8FAFC',
      translationLineColor: '#BAE6FD',
      textAlign: 'left',
      lineSpacing: 1.12,
      dropShadowOpacity: 2,
      dropShadowOffsetY: 4,
      dropShadowBlur: 8,
      backgroundColor: '#123047',
      backgroundOpacity: 8,
      backgroundBandHeightMode: 'custom',
      backgroundBandCustomLines: 4,
      backgroundBandVerticalPadding: 30,
      lyricsPosition: 'center',
      transitionAnimation: 'fade',
      transitionSpeed: 220,
      maxLinesEnabled: true,
      maxLines: 4,
      minFontSize: 28,
      xMargin: 8,
      yMargin: 1,
    }
  },
  {
    id: 'fullscreen-worship-gradient',
    title: 'Fullscreen Worship Gradient',
    description: 'Full-screen bundled background for simple services without separate media',
    settings: {
      ...baseOutputSettings,
      fontStyle: 'Montserrat',
      fontSize: 62,
      fontColor: '#FFFFFF',
      translationLineColor: '#FDE68A',
      dropShadowOpacity: 6,
      dropShadowOffsetY: 8,
      dropShadowBlur: 16,
      lyricsPosition: 'center',
      transitionAnimation: 'fade',
      transitionSpeed: 350,
      maxLinesEnabled: true,
      maxLines: 3,
      minFontSize: 36,
      fullScreenMode: true,
      fullScreenBackgroundType: 'media',
      fullScreenBackgroundColor: '#111827',
      fullScreenBackgroundPaint: {
        type: 'linear',
        angle: 135,
        stops: [
          { color: '#111827', position: 0 },
          { color: '#1D4ED8', position: 100 },
        ],
      },
      fullScreenBackgroundMedia: {
        url: '/backgrounds/worship-gradient.jpg',
        mimeType: 'image/jpeg',
        name: 'worship-gradient.jpg',
        size: 0,
        uploadedAt: Date.now(),
        bundled: true,
      },
      fullScreenBackgroundMediaName: 'Worship Gradient Background',
      fullScreenRestorePosition: 'lower',
      xMargin: 6,
      yMargin: 1.5,
    }
  },
  {
    id: 'fullscreen-stained-glass',
    title: 'Fullscreen Stained Glass',
    description: 'Full-screen church visual for hymns, liturgy, and traditional worship',
    settings: {
      ...baseOutputSettings,
      fontStyle: 'Lato',
      fontSize: 64,
      fontColor: '#FFFFFF',
      translationLineColor: '#FCD34D',
      bold: true,
      dropShadowOpacity: 7,
      dropShadowOffsetY: 8,
      dropShadowBlur: 16,
      lyricsPosition: 'center',
      transitionAnimation: 'fade',
      transitionSpeed: 400,
      maxLinesEnabled: true,
      maxLines: 4,
      minFontSize: 34,
      fullScreenMode: true,
      fullScreenBackgroundType: 'media',
      fullScreenBackgroundColor: '#1A1A2E',
      fullScreenBackgroundPaint: {
        type: 'linear',
        angle: 145,
        stops: [
          { color: '#1A1A2E', position: 0 },
          { color: '#4C1D95', position: 100 },
        ],
      },
      fullScreenBackgroundMedia: {
        url: '/backgrounds/stained-glass.jpg',
        mimeType: 'image/jpeg',
        name: 'stained-glass.jpg',
        size: 0,
        uploadedAt: Date.now(),
        bundled: true,
      },
      fullScreenBackgroundMediaName: 'Stained Glass Background',
      fullScreenRestorePosition: 'lower',
      xMargin: 6,
      yMargin: 1.5,
    }
  },
  {
    id: 'fullscreen-blackout',
    title: 'Fullscreen Blackout',
    description: 'Plain full-screen black background for high-control projection environments',
    settings: {
      ...baseOutputSettings,
      fontStyle: 'Roboto',
      fontSize: 60,
      fontColor: '#FFFFFF',
      translationLineColor: '#FDE047',
      bold: true,
      borderColor: '#000000',
      borderSize: 1,
      dropShadowOpacity: 5,
      dropShadowOffsetY: 6,
      dropShadowBlur: 10,
      lyricsPosition: 'center',
      transitionAnimation: 'none',
      transitionSpeed: 150,
      maxLinesEnabled: true,
      maxLines: 3,
      minFontSize: 36,
      fullScreenMode: true,
      fullScreenBackgroundType: 'color',
      fullScreenBackgroundColor: '#000000',
      fullScreenRestorePosition: 'lower',
      xMargin: 5,
      yMargin: 1.5,
    }
  },
  {
    id: 'hymn-fullscreen-texture',
    title: 'Hymn Fullscreen Texture',
    description: 'Traditional full-screen hymn display with bundled parchment-style texture',
    settings: {
      ...baseOutputSettings,
      fontStyle: 'Lato',
      fontSize: 68,
      fontColor: '#FFFFFF',
      translationLineColor: '#FDE68A',
      dropShadowOpacity: 5,
      dropShadowOffsetY: 7,
      dropShadowBlur: 12,
      lyricsPosition: 'center',
      transitionAnimation: 'fade',
      transitionSpeed: 400,
      maxLinesEnabled: true,
      maxLines: 4,
      minFontSize: 36,
      fullScreenMode: true,
      fullScreenBackgroundType: 'media',
      fullScreenBackgroundColor: '#1A1A2E',
      fullScreenBackgroundMedia: {
        url: '/backgrounds/hymn-texture.jpg',
        mimeType: 'image/jpeg',
        name: 'hymn-texture.jpg',
        size: 0,
        uploadedAt: Date.now(),
        bundled: true,
      },
      fullScreenBackgroundMediaName: 'Hymn Texture Background',
      fullScreenRestorePosition: 'lower',
      xMargin: 5,
      yMargin: 1.5,
    }
  },
  {
    id: 'transparent-large-venue',
    title: 'Transparent Large Venue',
    description: 'Large no-band overlay for temporary venues, LED walls, and strong background media',
    settings: {
      ...baseOutputSettings,
      fontStyle: 'Fira Sans',
      fontSize: 60,
      fontColor: '#F9FAFB',
      translationLineColor: '#FCD34D',
      bold: true,
      borderColor: '#000000',
      borderSize: 1,
      dropShadowOpacity: 8,
      dropShadowOffsetY: 9,
      dropShadowBlur: 14,
      backgroundOpacity: 0,
      lyricsPosition: 'lower',
      transitionAnimation: 'fade',
      transitionSpeed: 180,
      maxLinesEnabled: true,
      maxLines: 3,
      minFontSize: 34,
      xMargin: 4.5,
      yMargin: 2.5,
    }
  },
];

const baseStageSettings = { ...defaultStageSettings };

export const stageTemplates = [
  {
    id: 'default',
    title: 'Default',
    description: 'Reset to default stage display settings with standard configuration',
    settings: { ...defaultStageSettings }
  },
  {
    id: 'stage-classic',
    title: 'Classic Stage',
    description: 'Traditional three-line display with clear current/next/previous distinction',
    settings: {
      ...baseStageSettings,
      fontStyle: 'Inter',
      liveFontSize: 72,
      liveAlign: 'center',
      nextFontSize: 48,
      nextColor: '#A0A0A0',
      nextAlign: 'center',
      nextArrowColor: '#4ADE80',
      prevFontSize: 36,
      prevColor: '#606060',
      prevAlign: 'center',
      upcomingSongSize: 20,
      upcomingSongColor: '#A0A0A0',
      bottomBarSize: 18,
      transitionAnimation: 'fade',
      transitionSpeed: 200,
    }
  },
  {
    id: 'stage-minimal',
    title: 'Minimal Focus',
    description: 'Emphasizes current line with minimal distractions, subtle next line preview',
    settings: {
      ...baseStageSettings,
      fontStyle: 'Lato',
      backgroundColor: '#0A0A0A',
      liveFontSize: 84,
      liveAlign: 'center',
      nextFontSize: 40,
      nextColor: '#707070',
      nextItalic: true,
      nextAlign: 'center',
      showNextArrow: false,
      prevFontSize: 32,
      prevColor: '#404040',
      prevAlign: 'center',
      currentSongSize: 20,
      currentSongColor: '#E0E0E0',
      upcomingSongSize: 18,
      upcomingSongColor: '#808080',
      showTime: false,
      bottomBarSize: 16,
      bottomBarColor: '#C0C0C0',
      transitionAnimation: 'slide',
      transitionSpeed: 300,
      messageScrollSpeed: 4000,
    }
  },
  {
    id: 'stage-colorful',
    title: 'Colorful Guide',
    description: 'Color-coded lines for easy tracking with vibrant next-line indicator',
    settings: {
      ...baseStageSettings,
      fontStyle: 'Poppins',
      backgroundColor: '#1A1A2E',
      liveFontSize: 68,
      liveColor: '#60A5FA',
      liveAlign: 'center',
      nextFontSize: 52,
      nextColor: '#34D399',
      nextAlign: 'center',
      nextArrowColor: '#10B981',
      prevFontSize: 38,
      prevColor: '#9CA3AF',
      prevAlign: 'center',
      currentSongSize: 22,
      currentSongColor: '#F3F4F6',
      upcomingSongSize: 20,
      upcomingSongColor: '#D1D5DB',
      bottomBarSize: 18,
      bottomBarColor: '#E5E7EB',
      transitionAnimation: 'fade',
      transitionSpeed: 250,
      messageScrollSpeed: 3500,
    }
  },
  {
    id: 'stage-large-text',
    title: 'Large Text',
    description: 'Extra large fonts for visibility from distance, ideal for large stages',
    settings: {
      ...baseStageSettings,
      fontStyle: 'Roboto',
      liveFontSize: 96,
      liveAllCaps: true,
      liveAlign: 'center',
      nextFontSize: 56,
      nextColor: '#B0B0B0',
      nextAlign: 'center',
      nextArrowColor: '#22C55E',
      prevFontSize: 40,
      prevColor: '#707070',
      prevAlign: 'center',
      currentSongSize: 28,
      upcomingSongSize: 24,
      upcomingSongColor: '#B0B0B0',
      bottomBarSize: 20,
      transitionAnimation: 'fade',
      transitionSpeed: 150,
      messageScrollSpeed: 2500,
    }
  },
  {
    id: 'stage-compact',
    title: 'Compact View',
    description: 'Balanced sizing for smaller stages or confidence monitors',
    settings: {
      ...baseStageSettings,
      fontStyle: 'Open Sans',
      backgroundColor: '#121212',
      liveFontSize: 60,
      liveAlign: 'center',
      nextFontSize: 44,
      nextColor: '#9CA3AF',
      nextAlign: 'center',
      nextArrowColor: '#3B82F6',
      prevFontSize: 36,
      prevColor: '#6B7280',
      prevAlign: 'center',
      currentSongSize: 20,
      currentSongColor: '#F9FAFB',
      upcomingSongSize: 18,
      upcomingSongColor: '#9CA3AF',
      bottomBarSize: 16,
      bottomBarColor: '#D1D5DB',
      transitionAnimation: 'slide',
      transitionSpeed: 200,
    }
  },
];
